### PR TITLE
Create sample-applicants.ipynb

### PR DESCRIPTION
**Pull request by staeiou**
iPython notebook for generating test datasets for applicants

### CODE REVIEW

**Comment by dhuppenkothen** [comment]
I would suggest a small change: don't do a big for loop, but call numpy.random.choice with size=num_applicants and replace=True, then do a list comprehension for the names, and finally put all into a big numpy array.

**Comment by staeiou** [comment]
OK! This uses a pandas data frame and list comprehension, instead of a big for loop.

**Comment by bmcfee** [comment]
For our own sanity, can you make this so that the `name` column always appears first?

**Comment by staeiou** [comment]
Name column now appears first, with notebook code and datasets updated.

**Pull request merged**
